### PR TITLE
Add more description to script

### PR DESCRIPTION
**Pull request by wobbol**
Hey, this project is pretty cool! I started reading your code without reading the installation instructions and was massively confused about where the code runs.

This pull request is an attempt to rectify that situation.

Best Wishes,
N. Fontenot

### CODE REVIEW

**Review by alexnathanson — APPROVED** [review]
Thanks!

**Comment by alexnathanson** [comment]
If you're interested in learning more about the project, I'd be happy to hop on a call with you at some point to discuss it with you.

**Comment by wobbol** [comment]
Sure! Why not the Society of Privacy Advocates Mumble server as the place?

**Comment by wobbol** [comment]
@alexnathanson I have some complimentery work to what you did over the weekend here 
https://gist.github.com/wobbol/d64c1dd2c70a867bb80fd324eef7310f
I have zoom as well. I am not sure if that is more comfortable.

**Pull request merged**
